help_flag=0
for arg in "$@" ; do
  if [ -z "$state" ] ; then
    case ${arg} in
      -h|--help)
        help_flag=1
        ;;
      -b|--broker)
        state=broker
        ;;
      -p|--plugins)
        state=plugins
        ;;
      --database)
        state=database
        ;;
      --admin-name)
        state=admin_name
        ;;
      --admin-pass)
        state=admin_pass
        ;;
      --user-name)
        state=user_name
        ;;
      --user-pass)
        state=user_pass
        ;;
      --assetstore)
        state=assetstore
        ;;
      --girder-host)
        state=girder_host
        ;;
      --girder-port)
        state=girder_port
        ;;
      --girder-scheme)
        state=girder_scheme
        ;;
      *)
        passthrough_args[${#passthrough_args[@]}]="$arg"
        ;;
    esac
  else
    case ${state} in
      broker)
        CELERY_BROKER="$arg"
        state=
        ;;
      plugins)
        GIRDER_PLUGINS="$arg"
        state=
        ;;
      database)
        MONGODB_URL="$arg"
        state=
        ;;
      admin_name)
        ADMIN_NAME="$arg"
        state=
        ;;
      admin_pass)
        ADMIN_PASS="$arg"
        state=
        ;;
      user_name)
        USER_NAME="$arg"
        state=
        ;;
      user_pass)
        USER_PASS="$arg"
        state=
        ;;
      assetstore)
        ASSETSTORE_PATH="$arg"
        state=
        ;;
      girder_host)
        GIRDER_HOST_NAME="$arg"
        state=
        ;;
      girder_port)
        GIRDER_HOST_PORT="$arg"
        state=
        ;;
      girder_scheme)
        GIRDER_HOST_SCHEME="$arg"
        state=
        ;;
    esac
  fi
done

