help_flag=0
for arg in "$@" ; do
  if [ -z "$state" ] ; then
    case ${arg} in
      -h|--help)
        help_flag=1
        ;;
      --gc)
        DOCKER_GC=1
        ;;
      --nogc)
        DOCKER_GC=0
        ;;
      -b|--broker)
        state=broker
        ;;
      -e|--exclude-images)
        state=exclude
        ;;
      -p|--plugins)
        state=plugins
        ;;
      --docker-host)
        state=docker_host
        ;;
      --docker-port)
        state=docker_port
        ;;
      --docker-scheme)
        state=docker_scheme
        ;;
      --girder-host)
        state=girder_host
        ;;
      --girder-port)
        state=girder_port
        ;;
      --girder-scheme)
        state=girder_scheme
        ;;
      *)
        passthrough_args[${#passthrough_args[@]}]="$arg"
        ;;
    esac
  else
    case ${state} in
      broker)
        CELERY_BROKER="$arg"
        state=
        ;;
      plugins)
        WORKER_PLUGINS="$arg"
        state=
        ;;
      exclude)
        USER_EXCLUDE_IMAGES="$arg"
        state=
        ;;
      docker_host)
        DOCKER_HOST_NAME="$arg"
        state=
        ;;
      docker_port)
        DOCKER_HOST_PORT="$arg"
        state=
        ;;
      docker_scheme)
        DOCKER_HOST_SCHEME="$arg"
        state=
        ;;
      girder_host)
        GIRDER_HOST_NAME="$arg"
        state=
        ;;
      girder_port)
        GIRDER_HOST_PORT="$arg"
        state=
        ;;
      girder_scheme)
        GIRDER_HOST_SCHEME="$arg"
        state=
        ;;
    esac
  fi
done
