version: 2
jobs:
  test_all:
    docker:
      - image: circleci/node:8
    working_directory: ~/project

    steps:
      - checkout
      - run: yarn --version
      - run: node --version
      - run:
          name: Install web deps
          command: yarn
      - run:
          name: Run web tests
          command: yarn test
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash) -f test/coverage/cobertura-coverage.xml

      - store_artifacts:
          path: test/coverage/html

      - save_cache:
          paths:
            - node_modules
          key: web-dependencies-{{ checksum "yarn.lock" }}

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_all
      - release:
          requires:
            - test_all
          filters:
            branches:
              only: master
