version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.0-stretch-browsers
    working_directory: ~/project

    steps:
      - checkout
      - run: yarn --version
      - run: node --version
      - run:
          name: Install web deps
          command: yarn
      - run:
          name: Run web tests
          command: yarn test
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash) -f test/coverage/cobertura-coverage.xml

      - store_artifacts:
          path: test/coverage/html

      - save_cache:
          paths:
            - node_modules
          key: web-dependencies-{{ checksum "yarn.lock" }}
